"""modificacion

Revision ID: 89aa2646be23
Revises: 2975329c1f3b
Create Date: 2016-05-20 17:07:56.149371

"""

# revision identifiers, used by Alembic.
revision = '89aa2646be23'
down_revision = '2975329c1f3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('mapa', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'mapa')
    ### end Alembic commands ###
